# Generated by Django 5.2 on 2025-05-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMCauth', '0002_alter_captchamodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchamodel',
            name='captcha',
            field=models.CharField(max_length=8),
        ),
    ]
